.PHONY: test
test:
	@pytest tests

.PHONY: install_requirements
install_requirements:
	@pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir -r requirements.txt

#install_requirements_dev
#lint
#black
#pytest_coverage
